CREATE TABLE IF NOT EXISTS source (
    id String,
    email_address String,
    first_name String,
    last_name String,
    address String,
    city String,
    county_name String,
    state String,
    zip String,
    website_source String,
    phone_number String,
    gender String,
    dob String,
    registration_date String,
    valid String,
    extra String,
    email_id String,
    ethnicity String,
    ownrent String,
    domain String,
    main_interest String,
    sub_interest String,
    latitude String,
    longitude String,
    uploaded String,
    country String,
    websource_id String,
    interest_ids String,
    DNC String,
    source String,
    first_name_norm String,
    last_name_norm String,
    zip_norm String
) ENGINE = MergeTree()
ORDER BY id;
