CREATE TABLE IF NOT EXISTS flag_preview (
    id String,
    email_address String,
    first_name String,
    last_name String,
    address String,
    city String,
    county_name String,
    state String,
    zip String,
    website_source String,
    phone_number String,
    gender String,
    dob String,
    registration_date String,
    valid String,
    extra String,
    email_id String,
    ethnicity String,
    ownrent String,
    domain String,
    main_interest String,
    sub_interest String,
    latitude String,
    longitude String,
    uploaded String,
    country String,
    websource_id String,
    interest_ids String,
    DNC String,
    source String,
    first_name_norm String,
    last_name_norm String,
    zip_norm String,
    first_name_cleaning_candidate UInt8,
    last_name_cleaning_candidate UInt8,
    name_cleaning_candidate UInt8,
    email_blank UInt8,
    email_syntax_failure UInt8,
    proposed_email_export_eligible UInt8,
    zip_state_assessable UInt8,
    geography_mismatch_candidate UInt8,
    run_id String DEFAULT '',
    processed_at DateTime DEFAULT now()
) ENGINE = MergeTree()
ORDER BY (run_id, id);
